### PR TITLE
Google SSO

### PR DESCRIPTION
**Pull request by isgoutham**
## Description

Google SSO login for ThirdEye dashboard. 
- Uses ember-simple-auth and torii frameworks.
- Extended ThirdEyeDashboardModule to support multiple idps
- ThirdEyeGoogleAuthenticator Implements Authenticator interface. Supports ThirdEyePrincipal properties and sessionDTO save
- Imported Google client library
- Enable flag from thirdeye/thirdeye-dashboard/config/dashboard.yml `authEnabled: true`.

- New configuration options - `thirdeye-dashboard/config/dashboard.yml`
- Setup properties
```
authProvider: google # others can be ldap, azure, github, etc
tokenURL: "https://oauth2.googleapis.com/token"
```
## TODOs:
* [ ] Login disable support in Local deployment 
* [x] google secrets load from env variables in `torii` providers in `thirdeye-frontend/environment.js` file

## Notes:
- To support other IDP, eg: `Azure AD`
> create `ThirdEyeAzureAuthenticator.java` , import azure dependencies and handle access token creation
> enable torii-azure adapter in `thirdeye-frontend/config/environment.js` and `torii.js`
> create `action` for azure-login

### CODE REVIEW

**Comment by isgoutham** [comment]
Need Frontend Enginerring support. torii framework in `environment.js` file is unable to read env variables. tried using `dotenv` and `process.env.KEY`. still its not working.

**Comment by isgoutham** [comment]
image
image

**Comment by isgoutham** [comment]
Following environment variables are to be created on stage and prod envs

> MYSQL_USER
MYSQL_HOSTNAME
MYSQL_PORT
THIRDEYE_DATABASE
MYSQL_PASSWORD
DRUID_USERNAME
DRUID_PASSWORD
POSTGRES_HOSTNAME
POSTGRES_PORT
POSTGRES_DATABASE
POSTGRESQL_USER
POSTGRESQL_PASSWORD
GOOGLE_CLIENT_ID
GOOGLE_AUTH_REDIRECT_URL
GOOGLE_CLIENT_SECRET

**Review by venkatvghub — APPROVED** [review]
LGTM

**Pull request merged**
